version: v1.3.0

dsn: env://KRATOS_DSN

serve:
  public:
    base_url: http://127.0.0.1:9080/.ory/kratos/public/
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1:9080
        - http://localhost:9080
        - http://127.0.0.1:3000
        - http://localhost:3000
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
        - X-Requested-With
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:9080/
  allowed_return_urls:
    - http://127.0.0.1:9080
    - http://localhost:9080

  methods:
    password:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:9080/auth/error

    settings:
      ui_url: http://127.0.0.1:9080/auth/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:9080/auth/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:9080/auth/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:9080/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:9080/auth/login

    login:
      ui_url: http://127.0.0.1:9080/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:9080/auth/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: info
  format: text
  leak_sensitive_values: false

secrets:
  cookie:
    - env://KRATOS_COOKIE_SECRET
  cipher:
    - env://KRATOS_CIPHER_SECRET

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 12

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: env://KRATOS_SMTP_CONNECTION_URI
